title: Lee Yousef & Associates Real Estate Video Blog
description: Learn all the tips, tricks and more for buyers and sellers in the Calgary Area Real Estate Market

#for the navbar links.
custom_links:
  # - title: Our Listings
  #   url: http://www.calgaryareahousesforsale.com/featured/

contact_link: false


client:
  market: Calgary
  name: Lee Yousef
  brand: 'Lee Yousef & Associates'
  brokerage: 'CIR Realty'
  address: '707 10 Ave SW Calgary, Alberta T2R 0B3'
  phone: 403-689-3839
  email: recruitment@LeeYousef.com
  #Dont Include http://
  url: leeyousefrecruitme.wixsite.com/joinourteam
  # if forms put '/homevalue/' or '/homesearch/'
  homeeval: '#contact'
  homeeval_txt: Private Consultation
  homesearch: '#'
  homesearch_txt: '#'
  VR_form: 'http://oi.vresp.com?fid=f1b4aa14de'


# social links
socials:
  facebook: 'https://www.facebook.com/leeyousefrealestate'
  linkedin: 'https://ca.linkedin.com/in/lee-yousef-b8190340'
  gplus: 'https://plus.google.com/117612973095930427295'
  youtube: 'https://www.youtube.com/channel/UCCZEGY37lAtpOD6fZ44XWfA'
  twitter: 'https://twitter.com/leeyousef'
  instagram: '#'
  pinterest: '#'
  zillow: '#'
  trulia: '#'
  yelp: 'https://www.yelp.com/biz/lee-yousef-and-associates-calgary'
  podcast: 'http://leeyousef.blogspot.com/feeds/posts/default?alt=rss'

#podcast settings
podcast:
  # Something Real Estate Podcast
  title: Calgary Real Estate Podcast
  categories:
    - category: 'News &amp; Politics'
  image:
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- market -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from --client brand-- - your professional --market-- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Calgary, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author:

#layout options
# if we want review buttons --
review_sm_icons: false
audit_header: false

#image settings
images:
  hero_image_path: '/img/yousef_newblog.jpg'
  hero_logo_path: '/img/ly_logo_white.png'
  hero_text: 'Real Estate Training Blog'
  hero_background_hex: "#16AFBB"
  client_headshot_path: '/img/lee_yousef_headshot.jpg'

#colors
brand_hex: '#16AFBB'
theme_text: '#2a2a28'
theme_color: "#fff"
testimonial_fontcolor: '#fff'

#make testimonial container match brand color
# testimonial-container-brand_color: true
